### ISSUE TITLE
Setup in Docker

### ISSUE THREAD

**Issue by jankrynauw** [tkim/emsx_api_doc#2]
Bloomberg confirmed that the Server Side EMSX API licence works in Docker.

This last part is a 'human in the loop part' - It is not clear how this would work in a docker environment? Somewhere the logic does not make sense?  We've spent quite a bit of time with Bloomberg support already but no luck here?

**Comment by jankrynauw** [comment]
Sharing an example Dockerfile would be ideal.

**Comment by tkim** [comment]
Not in the scope
